package Cadastro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cauec
 */
public class Cadastro extends javax.swing.JFrame {
Conexao conexao = new Conexao();

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        conexao.Conecta();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtextNome = new javax.swing.JFormattedTextField();
        jtextEmail = new javax.swing.JFormattedTextField();
        jtextSenha = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonAdm = new javax.swing.JCheckBox();
        buttonFunc = new javax.swing.JCheckBox();

        jLabel2.setText("jLabel2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/b9376f662190a9e43827ed3e3c013149.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de funcionário");
        setMinimumSize(new java.awt.Dimension(680, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/b9376f662190a9e43827ed3e3c013149.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-110, -50, 460, 570);

        jtextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jtextNome);
        jtextNome.setBounds(430, 120, 210, 22);

        jtextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jtextEmail);
        jtextEmail.setBounds(430, 190, 210, 22);

        jtextSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jtextSenha);
        jtextSenha.setBounds(430, 260, 210, 22);

        jLabel3.setText("Nome ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 90, 41, 16);

        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 160, 41, 16);

        jLabel6.setText("Senha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 230, 36, 16);

        jLabel7.setText("Permissão");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(430, 300, 70, 16);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 380, 100, 25);

        buttonAdm.setText("Administrador");
        buttonAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdmActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAdm);
        buttonAdm.setBounds(430, 330, 109, 25);

        buttonFunc.setText("Funcionário");
        buttonFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFuncActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFunc);
        buttonFunc.setBounds(550, 330, 100, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNomeActionPerformed

    private void jtextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextEmailActionPerformed

    private void jtextSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdmActionPerformed

    private void buttonFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox buttonAdm;
    private javax.swing.JCheckBox buttonFunc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField jtextEmail;
    private javax.swing.JFormattedTextField jtextNome;
    private javax.swing.JFormattedTextField jtextSenha;
    // End of variables declaration//GEN-END:variables
}
